/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caro.client;

import caro.common.CPiece;
import java.awt.Dimension;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author tunado
 */
public class Rewatch extends javax.swing.JFrame {

    ListenServer listenServer;
    static JGoban Goban;
    static FileInputStream fis;
    static DataInputStream dis;
    static ScheduledExecutorService executorService;
    public Rewatch(ListenServer listenServer) {
       
        initComponents();
        this.listenServer = listenServer;
        setLocationRelativeTo(null);
        Goban = new JGoban();
        Goban.setPreferredSize(new Dimension(500,500));

        panelCaro_rw.setViewportView(Goban);

        Goban.Sakiyomi = true;
        Goban.Kinjite = true;

        Goban.init(500, 500);
        Goban.Initialize();
        Goban.Draw();
        try {
            //Bước 1: Tạo đối tượng luồng và liên kết nguồn dữ liệu
            fis = new FileInputStream("data.txt");
            dis = new DataInputStream(fis);
            lblName1.setText(dis.readUTF());
            lblName2.setText(dis.readUTF());
           } catch (IOException ex) {
             ex.printStackTrace();
        } 
        executorService = Executors.newSingleThreadScheduledExecutor();
        executorService.scheduleAtFixedRate(Rewatch::myTask, 0, 1, TimeUnit.SECONDS);
    }
    private static void myTask() {
        
          try {
            int a;
            CPiece[][] p = new CPiece[25][25];
            if(dis.available()>0){
                for (int i = 0; i < 25; i++) {
                     for (int j = 0; j < 25; j++) {
                        a = dis.readInt();
                        p[i][j]= new CPiece();
                        p[i][j].State = a;
                        System.out.print(a+" ");
                    }
                    System.out.println("");
                }
                System.out.println("----------------");
                Goban.Pieces = p;
                Goban.Draw();
                
            }
            else{
            fis.close();
            dis.close(); 
            executorService.shutdown();
            System.out.println("end");
            }
            
             } catch (IOException ex) {
             ex.printStackTrace();
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCaro_rw = new javax.swing.JScrollPane();
        lblName1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        btnExitRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCaro_rw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCaro_rwMouseClicked(evt);
            }
        });

        lblName1.setText("PLAYER 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("X");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("O");

        lblName2.setText("PLAYER 2");

        btnExitRoom.setText("EXIT");
        btnExitRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitRoomMouseClicked(evt);
            }
        });
        btnExitRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(panelCaro_rw, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblName1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName2))
                    .addComponent(btnExitRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelCaro_rw, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName1)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblName2))
                        .addGap(47, 47, 47)
                        .addComponent(btnExitRoom)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelCaro_rwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCaro_rwMouseClicked
        
    }//GEN-LAST:event_panelCaro_rwMouseClicked

    private void btnExitRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitRoomMouseClicked
        // TODO add your handling code here:
        try {
           
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnExitRoomMouseClicked

    private void btnExitRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExitRoom;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JScrollPane panelCaro_rw;
    // End of variables declaration//GEN-END:variables
}
